language: ruby 
rvm:
 - 1.9.3
 - 2.0.0
 - rbx-18mode
 - rbx-19mode
 - ruby-head
script: "bundle exec rspec"
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
notifications:
  email: false
